apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: demomongo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: pv
  resources:
    requests:
      storage: 1Gi
